### PR TITLE
Create giphy.service

### PR DESCRIPTION
**Pull request by bwets**
Use this to have a systemd service that can start the integration at startup. Put it in /etc/systemd/system/giphy.service

### CODE REVIEW

**Comment by ramnes** [comment]
Hi @bwets, thanks for your pull request!.

Ping @Lujeni and @ultrabug, what do you think of having that file in the source tree?

**Comment by ultrabug** [comment]
Hello @bwets, thanks a lot for this proposal.

I have a few remarks first.

Putting the Environment on the .service file means you expect the users to modify it themselves but on Linux systems the `/usr/lib/systemd/system/` belongs to root:root so **we clearly need a better way to allow user config vs init script installation on the system**.

Maybe a simple documentation on how to set those env vars on various Linux distributions would allow us to remove these (`/etc/default/` for debian/ubuntu, `/etc/env.d/` for gentoo....) ?

```
Environment=MATTERMOST_GIPHY_TOKEN=tokenHere
Environment=MATTERMOST_GIPHY_HOST=xxx.xxx.xxx.xxx
Environment=MATTERMOST_GIPHY_PORT=5000
```

Also, since you may be the beginning of an upstream proposed init scripts for packagers, I believe we should put this service file on an `init` folder ?

**Comment by BenSchumacher-cjf** [comment]
If you put the file under `~/.config/systemd/user` it starts as a userspace programm. This should fix @ultrabug problem

**Comment by hanzei** [comment]
If you put the file under ~/.config/systemd/user it starts as a userspace programm. This should fix @ultrabug problem

**Comment by paladini** [comment]
What about crontab? I'm using this approach to fix `mattermost-integration-giphy` startup problem: http://stackoverflow.com/a/29247942/2127383

What do you think about that?

**Comment by hanzei** [comment]
@paladini Why would you use cron over systemd? Cron ist quite old, see http://unix.stackexchange.com/questions/278564/cron-vs-systemd-timers

**Comment by rayphi** [comment]
My Solution for this Problem is http://supervisord.org/
```
# /etc/supervisor/conf.d/2-mattermost-integration-giphy.conf
[program:giphy]
command=/usr/bin/python /var/www/mattermost-integration-giphy/run.py
environment=MATTERMOST_GIPHY_TOKEN='xxx',MATTERMOST_GIPHY_HOST='127.0.0.1',MATTERMOST_GIPHY_PORT='5000',GIPHY_API_KEY='xxx',RATING='R'
autostart=true
autorestart=true
priority=1
```

**Comment by ramnes** [comment]
Since there are a lot of different solutions to handle this and that there is not one that fits all use-cases, I'll go ahead and close this.

Maybe this is something we could have in the documentation, instead?

Thanks everyone for your effort!

**Pull request closed without merging**
