### PR TITLE
Dockerize this integration

### PR DESCRIPTION
**Pull request by pichouk**
I use all my apps into Docker, so I dockerized this integration. It is quite simple. I add some documentation (based on Linux one) to allow easy build and deployment with Docker.

### CODE REVIEW

**Comment by Lujeni** [comment]
Hello @pichouk,

Thanks for taking the time to open this issue.
We will review this MR and integrate it very soon.

**Comment by pichouk** [comment]
I just remember that I suggest this pull request. Anything new on it ?
On my side I came up with 2 suggestions :
1 ) It also could be interesting to use Alpine based docker image of python (much small docker image).
2) We could think of an automated build on docker hub, based on this repository. I really think some people will appreciate to deploy only with a docker run command :)

If you have any questions/suggestions, let me now.

**Comment by pichouk** [comment]
After running some test on my production instance, it appears that it works great with python alpine-base docker image. Image is now 82.1MB instead of 737MB

**Comment by Lujeni** [comment]
All is good for me thanks again @pichouk !

**Pull request merged**
